### ISSUE TITLE
双击AUTO.bat闪退？

### ISSUE THREAD

**Issue by haibugouing** [VonSdite/Auto_Shadowsocks#1]
官网好像被墙了？

**Comment by VonSdite** [comment]
双击闪退的话， 可能是因为bat download下来的换行没了， 你在github打开复制一份到你的bat应该就可以了。 现在又可以用了哈哈哈。
呃，  有问题 发邮件会快一点 。 122691411@qq.com

**Comment by VonSdite** [comment]
闪退 原因也可能是我之前更改的正则规则 忘记上传了。 导致爬取不到密码》。。我刚刚上传了
