### ISSUE TITLE
关于脚本填写密码时多加了  \n

### ISSUE THREAD

**Issue by MIAOFC** [VonSdite/Auto_Shadowsocks#10]
gui-config.json    中的代码
这是脚本添加的信息，在密码的尾部脚本自己添加了 \n ,如何解决或者是修改哪里？ 谢谢！
    "server": "b.isxa.bid",
      "server_port": 11012,
      "password":  "96295977\n",
      "method": "aes-256-cfb",
      "plugin": "",
      "plugin_opts": "",
      "remarks": "shao",
      "timeout": 5
    },
 
这是扫描二维码添加的信息   
{
      "server": "a.isxa.bid",
      "server_port": 19025,
      "password": "42728119",
      "method": "aes-256-cfb",
      "plugin": "",
      "plugin_opts": "",
      "remarks": "",
      "timeout": 5

**Comment by VonSdite** [comment]
哇哇哇哇！！ @MIAOFC  对哦！原来我最近使用这个上不了网是这个原因。

感谢。 我已修复了！！  可以随便翻墙了！！！

**Comment by MIAOFC** [comment]
不谢，用你的脚本，还没和你道谢呢。谢谢。 @VonSdite

**Comment by MIAOFC** [comment]
不谢，用你的脚本还没和你道谢呢，谢谢。 @VonSdite
