### ISSUE TITLE
ss.ishadow.net被墙了？

### ISSUE THREAD

**Issue by soulfy** [VonSdite/Auto_Shadowsocks#2]
如题

**Comment by VonSdite** [comment]
今天又可以用了！！ 
https://ss.ishadowx.net/

**Comment by VonSdite** [comment]
go die.... 八点多一点的时候可以上的， 现在又又又上不去了

**Comment by VonSdite** [comment]
噢。 我发现个问题， 不能上的话可能 你用的是 校园网， 我刚切换成电信网可以上

**Comment by soulfy** [comment]
我用的公司网。。 通过代理才可以访问，可能跟服务商有关系吧

**Comment by VonSdite** [comment]
可能是吧... 我现在还是可以直接访问的...
