### ISSUE TITLE
关于翻墙存在的问题！（2）

### ISSUE THREAD

**Issue by VonSdite** [VonSdite/Auto_Shadowsocks#5]
# 注意

- 爬取的服务器会在 0，6, 12, 18, 24点时重启服务器，导致你翻不了墙。服务器重启之后大约十几分钟后才能翻墙

- 免费的服务器毕竟是免费的，翻墙实际不是很稳定，小飞机有流量跳动的动画时，表示稳定翻墙中。开着小飞机翻墙时，发现连不上，多刷几次应该就可以了

**Comment by soulfy** [comment]
ss.ishadow.net上拿到的免费服务器地址， ping不通， telnet端口也不通。。

**Comment by VonSdite** [comment]
emmm。 服务器填上了不能翻墙那就是 那边免费服务器的原因了。 应该是这个月的特殊时期， 下个月应该就可以了吧

**Comment by qxc2016** [comment]
下载后，环境也搭建好了，但是运行Auto.bat脚本时，提示命令行找不到 ……不知道为什么

**Comment by VonSdite** [comment]
命令行提示
错误: 没有找到进程 "shadowsocks.exe"。 这一句是表明当前进程中没有shadowsocks.exe的进程，所以找不到， 有这句提示是正常且正确的、
