### ISSUE TITLE
SS换了个新网站

### ISSUE THREAD

**Issue by RSDKing** [VonSdite/Auto_Shadowsocks#8]
目前是这个https://go.ishadowx.net/ 希望VonSdite能修改一下

**Comment by soulfy** [comment]
然而， 我这里口令能抓了， 但代理依然无法用。。

**Comment by Dorllen** [comment]
我觉得ss的代理被gtw限制了，很慢！

**Comment by VonSdite** [comment]
..... 
http://ss.ishadowx.com/ 这个网站是会跳转到 https://go.ishadowx.net/ ， 所以这个网址变不变倒是无所谓。。。

现在我用的时候， 经常是不能翻墙的。。。。 免费服务器 太渣了。。 要不就买一个吧。。

**Comment by RSDKing** [comment]
在哪买啊？ @VonSdite

**Comment by VonSdite** [comment]
@RSDKing ss那个网站上去了往下拉就有服务器卖了...或者百度或google， 能找到很多的》。。。
